AlexsLemonade/scpca-docs

- components/dictionary.txt
- docs/faq.md
Here I am adding in a FAQ addressing what type of genes are included in the index, #23. While doing this, I also included a link to the code used to generate the reference transcriptome used to make the splici index (addressing #12). I kept this pretty short and mentioned the number of genes and that they include protein-coding genes, pseudogenes, and non-coding genes. I also put in a brief sentence that the output files they receive will include all genes regardless of if they are detected or not. 
One thing I was wondering was if we want to add in a statement that we suggest removing any genes that are not detected or have mean gene expression of 0 before doing analysis or do we just leave that alone and not include anything on suggestions yet? 
In general I didn't go into too much …
> Describe what genes are included in the reference transcriptome

- .gitignore
- docs/_templates/layout.html
Readthedocs deploy is broken because it can't build the epub. This PR adds the `_build` directory to gitignore and fixes the issue by changing the theme path for extending `layout.html`
> epub fixes

- docs/faq.md
Closes #26. Here I added in a section to address how to convert the SCE objects that we provide to Seurat objects. Right now I have only included how to work with the objects that contain RNA-seq data with/without CITE-seq data, but I'm anticipating that we would have to update these instructions for cell hashing data at a later date.
In order to do the conversion, I originally was going to use `as.Seurat()` which is suggested in the [vignette from Seurat](https://satijalab.org/seurat/archive/v3.1/conversion_vignette.html), however this requires normalized counts to be stored as `logcounts` in the sce object. Since we do not provide normalized sce objects, I tried a few ways around this, but then after some searching around realized that the best way to do this would probably be to grab …
> Add FAQ on how to convert the SCE objects to Seurat objects

- components/dictionary.txt
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #45. Here I am updating the docs to reflect the most recent changes that will be present in the newest release of `scpca-nf`. There are three main points that I updated in the docs. 
1. Changing the resolution mode of alevin-fry to `cr-like-em`. Here I edited the docs to return to the original contents in which we use `cr-like-em` as the resolution for alevin-fry rather than `cr-like.`
2. Updating the discussion on `emptyDrops` filtering to be about `emptyDropsCellRanger`. Here I noted that we are using `emptyDropsCellRanger` and removed the mention of `lower` since that argument is no longer used in that function. I also added in a short discussion on how the ambient profile is calculated as that is one of the main differences between `emptyDrops` and `emptyDropsCellRanger`. …
> Update processing and filtering information in docs to reflect scpca-nf release 0.1.3

- docs/processing_information.md
- docs/sce_file_contents.md
Closes #53. Here, I am adding a short note in the filtering section of the processing information to note that if a library does not meet the assumption of `emptyDropsCellRanger`, that it will be filtered using a hard cutoff instead. 
I also added in the additional fields in the metadata `filtering_method` and `umi_cutoff` to the `sce_file_contents` page. I chose to keep everything in the metadata for the sce as one large table, but thought about the idea of breaking out the three pieces of metadata that are only present for the filtered data and include in a small separate table below the first table (similar to how we do the `cell metrics` section). If reviewers like that idea, I can break out the table, but I wasn't sure if this was completely necessary.
> Add information about hard UMI cutoff for filtering

- docs/download_files.md
Closes #57. Here I incorporated the new illustrations that were created by @dvenprasad. I tested building the docs and looked to be sure that they appear as they are supposed to showing the new name for the `single_cell_metadata.tsv` file. 
I also stacked this on #56 so that we can merge all changes related to adding the bulk metadata together.
> Update illustrations for download files 

- docs/processing_information.md
Closes #62. This PR removes the line in the processing information section that stated `data available soon` since we now have bulk data available on the portal.
> Remove data available soon from bulk RNA-seq processing section

- docs/download_files.md
Closes #49. Here I added information on what is included for libraries that are spatial transcriptomics libraries. In the section at the beginning that shows the illustrations of expected files, I added a few sentences on what to expect if a sample downloaded contains a library with spatial transcriptomics. This is where I noted that users should expect a folder that contained all of the spatial output and linked to a separate section at the end of the download section specifically describing the contents of the folder for spatial libraries. I also added a note in the section about downloading a specific sample, stating that if a specific sample they chose to download contained a spatial library that the file structure they saw would be different then the typical single cell output. 
At …
> Add description of spatial files to download files section

- components/dictionary.txt
- docs/faq.md
Closes #77, #73, and #76. 
Stacked on #70. 
I'm adding the three FAQs for multiplexed samples here, what is a multiplexed sample, what are est. demux cell counts, and why do multiplexed samples have est. demux cell counts. I decided to pull this together into one PR, because I thought it would make sense for reviewers to look at all of these together as they are all somewhat linked, especially the ones about estimated demux cell counts. 
I also stacked this on #70 so that I could link to some of the information in the processing and sce file contents docs in answering the questions. 
The one main question I have is if we want to explicitly say that we are reporting the cell counts using genetic demultiplexing? Right now as things are that's what we are using, but I know there was a …
> Addition of Multiplex FAQs

- docs/faq.md
- docs/getting_started.md
Closes #74. 
⚠️ Stacked on #83 ⚠️ 
Here I added a section to the `Getting started with an ScPCA dataset` that includes special considerations for multiplexed samples. I was unsure about the level of detail that we wanted, but based on the two points described in #74, I was sure to include a description of what a multiplex sample is and information on how to filter to the sample of interest. 
I also included a statement about how the initial analysis that is described in the beginning of the getting started section for single sample libraries - filtering, normalization, dimensionality reduction - can be performed as usual. Then I included some details about demultiplexing and identifying which cells belong to which samples, explaining that those results are already summarized and providing …
> Getting started section for multiplexed samples

- docs/getting_started.md
Closes #88 
Here I added a link to the downstream analyses repo in the getting started section. I wasn't quite sure how much detail we wanted to put here, but I wanted to emphasize that there is a workflow that processes samples in parallel and performs the steps mentioned in the getting started doc. I think this is probably the only place in the docs where it makes sense to include a link. 
Also there's some trimming of white space, so apologies for the extra lines in the diff.
> Add link to downstream analyses repo 

- .github/workflows/spell-check.yml
- components/dictionary.txt
- docs/processing_information.md
Closes #90 and #96 
This PR starts the documentation of post processing of gene expression data to now include filtered, normalized data and PCA/UMAP embeddings. I started by adding a section to the `processing_information.md` section of the docs that comes after the post alevin-fry section but before the CITE-seq section. I kept things relatively simple by just describing what was done, what thresholds were used, etc. Let me know if I should include more detail here. 
I also created a `development` branch before doing this and filed this PR to that branch so that all changes related to upcoming releases on ScPCA that are not yet available go to `development` first. 
One thing I noticed while doing this is that we have some discrepancies between how we tell people to remove low quality …
> Include section on post processing of gene expression data in processing information part of docs

- docs/sce_file_contents.md
Closes #93. 
This PR updates the `sce_file_contents.md` section to include mention of the processed SCE object and any items that can be specifically found in the processed SCE object. 
I made a few updates throughout here: 
- I added a section below the `colData` tables discussing the presence of the `ccdl_filter` column that will be found in the processed objects. I mentioned briefly here that we do filtering, but not how the criteria are chosen. Instead I direct them to the processing information. The point I wanted to get across here is that there will be an additional column in the `colData` but they should all be labeled as `Keep` if they are in the processed object. 
- I added any of the new changes that have been made to the metadata list for both the filtered objects and then the …
> Update SCE file contents to include processed SCE objects

- docs/getting_started.md
Closes #98 
Here I made some tweaks to the getting started section to mention that we now have a processed object and that users can directly work with that rather than the filtered object. I modified some of the language at the beginning to describe all three files now and suggested that users work with the processed object. I also updated the section on reading in files to use the processed object rather than the filtered object. 
The other thing I added here was a small section on working with the processed objects and had a few examples on how to access some of the things that are unique to these objects. In this section, I included a statement that these objects are ready for downstream analysis including clustering, but didn't provide a ton of detail. I wasn't sure how much we …
> Update getting started section to include mention of processed objects

- docs/processing_information.md
- docs/sce_file_contents.md
Closes #106 
This PR adds information about CITE-seq processing into the portal docs (along with some misc typo/wording fixes), based on work done in:
- https://github.com/AlexsLemonade/scpca-nf/pull/312 (filtering; merged) 
- https://github.com/AlexsLemonade/scpca-nf/pull/325 (normalization; still under review)
Any feedback about the level of detail I've added or whether I've missed a spot is great here! I'm opening this as a draft only because normalization details may change during review of the code itself, and I'll mark this as formally ready for review once the code is finalized. In the meantime feel free to poke around and leave feedback as needed!
> Add CITE post-processing to docs

- components/dictionary.txt
- docs/download_files.md
- docs/faq.md
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #112 
This PR updates `sce_file_contents.md` and `processing_information.md` to reflect our shift in ADT filtering strategy. I also updated some phrasing (which I feel both ways about?) to say "negative/isotype control" instead of either negative or isotype, to cover more ground... Phrasing feedback welcome here!
In these files and `faq.md`, I also changed some wording around to refer more to ADT counts, not CITE-seq counts, and similar. I updated associated rel links where appropriate but this can definitely use some more 👀 !
> Update docs: no ADT filtering & ADT modality

- components/dictionary.txt
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #120 
Two main updates:
- There is an `adt_normalization` field now in the metadata for CITE-seq samples
- We no longer fail if size factors are 0. Instead, `log1p`.
Let me know if what I've written is clear, thanks!
> Updates for ADT normalization

- docs/getting_started.md
Closes #113 
This PR updates `getting_started.md` with information on how users can get started with filtered and/or processed ADT data. I described how users can filter cells based on ADT stats and normalize ADT counts, with considerations for both `filtered.rds` and `processed.rds`. I included two resources links - OSCA and a Seurat vignette.
Something I thought about but didn't do (yet?) is expand the table with `subsets_mito_sum` to indicate the `subsets_adt_*` QC stats, since this seemed out of scope for that section (even though it's a thing that might get returned if there is a CITEseq altexp).
Let me know where we could use a little more or less detail!
> Update `getting_started` with ADT post-processing 

- docs/sce_file_contents.md
Closes #122 
Happily there weren't really any broken xrefs, just 1 as described in #122 :tada:
I fixed that one and then added a couple `()` where needed at the end of functions.
> Little docs fixes

- docs/download_files.md
- docs/getting_started.md
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #124 
This PR updates docs to reflect changes implemented for ADT filtering in `scpca-nf v0.5.3`. Changes were made to indicate that sometimes filtering fails if `cleanTagCounts()` cannot reliably determine cells to filter (I decided not to get into the weeds of _why_ `cleanTagCounts()` might have decided this, just that it did). In this case, log-normalization is performed, and the SCE metadata will state `No filter` for the filtering method.
Please let me know if we think there are other spots where text needs updating, and whether the updates I've made here are clear, thanks!
> Update ADT filtering sections

- components/dictionary.txt
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #128 
This PR adds documentation for the graph-based clustering that is heading into `scpca-nf`.
For now I'm opening this as a draft PR, since the details added to `docs/processing_information.md` _may_ change as https://github.com/AlexsLemonade/scpca-nf/pull/405 gets wrapped up. Once that other PR that is actually adding the clustering workflow is all set, I will update here as needed and mark as ready for review.
> Add docs for clustering

- components/dictionary.txt
- docs/download_files.md
- docs/sce_file_contents.md
Closes #145 
This PR expands the current section on gene expression file contents to include both SCE and AnnData objects. 
- I created a short introduction section that states gene expression data is available as either SCE or AnnData. Then I created two large sections, one for SCE and one for AnnData (as mentioned in the outline of #145). 
- The two sections mostly mirror each other and each have a description of cell metrics, gene expression metrics, metadata, dim reductions, etc. Although the actual sections mirror each other, I tried to avoid repeating things that are present in both objects. For the cell and row metadata in AnnData objects, I provided links to the SCE section for things that are found in both and then a separate table for any additional information that is present …
> Description of AnnData contents

- docs/download_files.md
- docs/faq.md
- docs/sce_file_contents.md
Closes #149 
Closes #147 
Stacked on #162 
I removed the FAQ on "what if I want to work with python" and replaced it with a FAQ on how to work with the downloaded HDF5 files. I decided to mirror what we provide for working with RDS files, and thought it didn't make sense to have both FAQs there. 
I also expanded the RDS FAQ to include some links to both the getting started and the file contents sections, since I think both are helpful. I did the same in the HDF5 section. 
While I was here, I did some checking on the links to make sure that they still work, given some of the header changes we've made previously. I noticed some were broken because I used code formatting in the headings, but now I remember why we didn't have that before. The links don't work with the code formatting, so I …
> Update FAQs to account for AnnData

- docs/getting_started.md
Closes #164 
Here I continued with the progress I had started in #162 and modified the CITE-seq section to both refer to only the processed objects and add in AnnData objects. Generally, I follow the format I started in #162 to include an overview of the step or item (like filtering and QC) together but then show two separate commands for R and python. 
- Any duplicate commands for the processed and filtered objects have been condensed so that we only show how to work with the processed objects. This is what we did for the main section. 
- I condensed both accessing the ADT data and getting the raw/normalized counts into one code chunk for R and one for python. I'm curious what others think of this, but I think I like this better. I don't think we need a whole separate chunk for reading …
> Update CITE-seq section of getting started docs to include AnnData 

- components/dictionary.txt
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #160 
This PR makes some small adjustments to docs to sync up what we say about cell typing here to where the cell types actually live in the object. 
- I added a link for both SingleR and CellAssign papers to the processing information section on cell type annotation. 
- In that same section, I added a note about submitter annotations. 
- I included the `submitter_annotation` column in the cell metrics section. When adding this in, I chose to add this in the table that mentions items that are in both filtered and processed objects. I think this is the right place since if they are available they will be in all of the objects. 
- I standardized how we refer to the `cellassign_reference` and `singler_reference`. This matches changes made in …
> Update SCE contents and processing with cell type information

- .readthedocs.yaml
- docs/.readthedocs.yaml
Our builds are broken. I think this is why!
If this works and goes in, we'll need to file PRs to `development` and `documentation-improvements`.
> Add build.os argument to config

- docs/processing_information.md
- docs/sce_file_contents.md
Closes #142 
Note that this PR is getting merged into the new `documentation-improvements` branch that I made. This branch is protected and should be use for making all the pre-AnnData and pre-celltype changes. 
Here I updated the section on post processing alevin-fry to indicate that we always combine counts. I also added a sentence to the sce file contents to note that the `counts` matrix includes the counts from both spliced and unspliced cDNA and included a link to the processing information. 
I did include a sentence about the presence of the `spliced` assay in the object, but I'm unsure if we want to mention that or not... I'm curious about what others think.
> Update docs to note we always use spliced and unspliced cDNA

- .github/ISSUE_TEMPLATE/release-checklist.md
Closes #175 
This PR adds a new issue template with a checklist for releases. I used a similar format to the [release template that we have in `scpca-nf`](https://github.com/AlexsLemonade/scpca-nf/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md). I also tried to add some instructions to help if people are only releasing part of the updates that are present in `development`, especially because we are about to do that. Please check to make sure the instructions and additional comments are clear. 
One thing that I didn't do was add a version tag in the issue title. We have that for other release checklists, but here the tag is based on the day the docs get released. So instead, I added a note about updating the title to include the expected contents of the release. If others feel …
> Create release issue template

- docs/faq.md
⚠️  Stacked on #184.
I'm adding a FAQ directing users to the CHANGELOG section framed regarding new downloads breaking old code. Closes #132.
> Add FAQ directing people to CHANGELOG

- .github/ISSUE_TEMPLATE/release-checklist.md
- .github/PULL_REQUEST_TEMPLATE/to-main.md
- .github/pull_request_template.md
Here I'm making three changes:
1. Adding a checkbox to the release issue template to remind people to update the date of the CHANGELOG entry as applicable
2. Adding a PR template for merging to main that includes a checklist geared towards publishing a release
3. Adding a "main" PR template that just tells people to use the other template if they're targeting `main`.
> Add PR template for publishing to `main`

- docs/CHANGELOG.md
⚠️ _Stacked on #184_
Closes #187. I am adding a CHANGELOG entry that covers the following updates to downloads associated with https://github.com/AlexsLemonade/ScPCA-admin/issues/683:
* Access date in root directory of downloads
* README updates:
* Generated on date
* Citation section
> Add CHANGELOG entry for docs improvements epic

- components/dictionary.txt
- docs/CHANGELOG.md
- docs/faq.md
- docs/index.md
Closes #131. Here, I'm adding the initial version of the CHANGELOG. Per comments on that issue, this PR:
* Initializes the CHANGELOG file
* Adds intro text that covers where to find more information about downloads (i.e., workflow version and download generation date)
* Puts the CHANGELOG right after the FAQ section
~~Draft for now until I check the build and spell check. After that, I'll mark it as ready for review.~~ Ready for review!
> Initialize CHANGELOG section

- docs/CHANGELOG.md
Replaces the change log's first entry's title from Release Date placeholder to today's date: `2023.11.10`. This is the semver version of the date so it will be consistent with urls and the version on the side nav.
> set release date 2023.11.10

- .github/ISSUE_TEMPLATE/release-checklist.md
I noticed that the release page link was to `scpca-nf` when I cut the release from the `2023.11.10` tag this morning. This updates the release issue template to point to this repo's releases page. 
N/A
> Link to scpca-docs releases in release-checklist

- docs/getting_started.md
As pointed out here, https://github.com/AlexsLemonade/scpca-docs/issues/165#issuecomment-1813235397, some link parentheticals are in brackets, not parentheses. 
> It seems pretty reasonable. I will pick a nit, though – some of the publication references in the cell annotation section use `[]` instead of `()` and I don't know why.
This PR fixes those spots! Did I miss any, or notice anything else while we're here?
> Brackets to parentheses

- docs/faq.md
Closes #190 
Here I updated the FAQ on why participant IDs might be missing to explain what a participant ID is. We now include a participant ID for every sample, so any language about the ID being optional has been removed.
> Update FAQ for participant IDs

- docs/download_files.md
Closes #205 
Here, I added some new entries to the table that describes the contents of the metadata file that is included with download. We are now including `organism` as well as the other ontology terms for each sample, so we should include that information. I mostly took what was in the `ScPCA-admin` readme about the new entries, but condensed it to be more relevant to external users. 
I left in the description of NA/unknown for each of the fields except the disease ontology. I don't know where we would be missing a disease ontology since all samples should have a disease... Let me know if the level of detail that I included is okay.
> Add new metadata to download section 

- docs/sce_file_contents.md
Closes #194 
Closes #211 
Here, I've made some small docs changes:
- We now refer to unlabeled submitter cells as `"Submitter-excluded"` (not `NA`)
- We now include `cellassign_reference_organs` in the processed object metadata. I also tweaked the `cellassign_reference` description, what do you think of my wording?
> Update docs: CellAssign organs and unlabeled submitter cells

- docs/CHANGELOG.md
Closes #209 
Here, I've added text for a cell type annotation changelog. I decided to leave out some of the details that I had noted in #209, instead favoring linking to the relevant docs sections. As a consequence the changelog is actually pretty short. What do we think about this decision?
Note that I'm opening this as a Draft because we _absolutely do not want to merge anytime (super) soon_..!
> Add cell type changelog

- docs/processing_information.md
Closes #215 
This PR adds a very short section about merged processing. I don't think much more background is needed to review this PR! I'm honestly not sure if I've struck the right balance of level of detail; I did open with a bit more context than would be expected in this processing information docs, but it seemed like maybe a good idea because this section describes fundamentally different objects from the rest of the page? 
Let me know what you think and where I can expand or where I can reduce!
> Add documentation in processing_information for merged objects

- components/dictionary.txt
- docs/getting_started.md
- docs/processing_information.md
- docs/sce_file_contents.md
Closes #222
Closes #227 
This PR adds some documentation for xenograft and cell lines:
- In `processing_information.md`, I added text that there is no cell typing for cell lines, and I also pointed users to where they can figure out if their sample is a cell line....
- ....in table lines which I added into `sce_file_contents.md` for both SCE and AnnData objects
- I also added some little blurbs in `docs/getting_started.md` that if cell type methods are empty, there are no cell type methods.
Let me know if there are other spots I didn't think of that could use some additional docs, and/or any wording feedback!
> Document xenograft and cell line samples 

- docs/download_files.md
Quick change of `_cell_type_report.html` -> `_celltype-report.html`, as discussed in #226!
> Change celltype report name

- docs/download_files.md
While working on merged docs, I noticed this typo where filtered should have said processed.
I fixed this typo separately since it needs to make it into #208 for the anndata release; I can cherry-pick it in there (and cell type release PR) after this is goes in.
> Fix typo: filtered -> processed

- components/dictionary.txt
- docs/CHANGELOG.md
**Stacked on the cell type release PR**
This PR adds a bullet to the cell type `CHANGELOG` section to indicate that community-contributed datasets are also available. I wasn't exactly sure the right level of detail to include here, let me know what you think. Too much? Too little? Wrong details entirely?
We could also link the contributing page (https://scpca.alexslemonade.org/contribute) to give readers more context?
> Add community contributed data to changelog

- docs/download_files.md
**Stacked on cell type release PR**
The current chat in Slack reminded me that we need to tell users that they won't receive a report with their download if the library is from a cell line! My wording might be simplified as well here, lmk what you think.
> No cell type report download for cell lines

- docs/processing_information.md
**Stacked on celltype release branch**
Closes #246
Based on changes in https://github.com/AlexsLemonade/scpca-nf/pull/662/commits/c8364a1274a1f3db26fefd1d7877a83aad83aa76#diff-ebc8278a409c56e4a1cb2f282a109062be67a349c3cf22c2db5e69dccd204f92, I added a quick sentence that we* only run `CellAssign` if there are at least 30 cells. Is this enough, or should we give a tiny bit of "why"?
> Skip cellassign if >30 cells

- docs/processing_information.md
Closes #248 
This PR does what it says and changes some "library" -> "sample" in the processing docs for merged objects. I really only changed spots in the parts about downloading files, since it seemed to me that library _might_ be more appropriate in the meat of the processing description. For review, please give the whole section a quick skim (including parts not shown in the diff) and lmk if I should update other spots too, thanks!
> Change some language from libraries to samples

- docs/faq.md
- docs/merged_objects.md
Closes #221
In this PR and very well-named branch, I added a section to the FAQ about circumstances where there is no merged object. I think this could be two sections instead of one, but since each would be so small I started off by collapsing into one section. 
Please let me know what you think of the section title, whether it should be 1 or 2 sections, and whether I've hit all the right points or should expand/reduce anywhere!
> Add section to FAQ about projects without merged objects

- docs/sce_file_contents.md
I found an important typo to fix! This should have said `.obs`, not `.uns`.
Once this goes in, I'll cherry-pick into the 2 release draft PRs.
> Fix uns/obs typo

- .github/workflows/spell-check.yml
- docs/CHANGELOG.md
- docs/faq.md
- docs/getting_started.md
- docs/merged_objects.md
- docs/processing_information.md
- docs/sce_file_contents.md
- scripts/spell-check.R
Closes #241 🎉 
This PR _should_ 🤞 wrap up the merged object docs page. I added sections for experiment metadata (`uns`), reduced dimensions, and CITE-seq considerations.
I also made a couple other small changes:
- Gratuitous change to de-magrittr the spell check script
- Some parallel changes about that `discard` column, as in #261 
- Fixed some relative links throughout the docs that were not properly formatted, mostly a bunch of places that were missing a closing `>`!
- We missed a few spots in #258 to document `adt_id` (not `adt_name`!) in sce rowdata & anndata `.var`.
> Complete merged anndata docs

- .github/ISSUE_TEMPLATE/release-checklist.md
- components/dictionary.txt
- docs/CHANGELOG.md
- docs/download_files.md
- docs/faq.md
- docs/index.md
- docs/processing_information.md
While cherry-picking #271 into the cell type release branch, I noticed a couple changes had apparently happened in the cell type release branch only which were not properly reflected in `development`. This PR merges the cell type branch into `development`, so branches should now be more in sync!
> Sync up development

- docs/faq.md
I was working on the template READMEs for merged data and noticed a small typo in the header for one of the FAQs that I fixed here.
> Fix small typo in merged FAQ

- docs/conf.py
- docs/download_files.md
When downloading data from the portal, I noticed that the docs did not include the changes to the `age` field in the metadata table, so this updates that.
I also noticed that the "edit on github" link was going to wrong place (a 404 with an extra `docs/` in the path, so I tried to fix that too.
> Update name of age field

- docs/faq.md
- docs/merged_objects.md
Closes #282 
Here I updated the docs to account for projects with missing merged objects. 
- I noticed that we still describe the contents of multiplexed merged objects even though we don't provide them. I removed that section and replaced with a note that we don't merge any projects with multiplexed libraries. 
- I updated the FAQ with another bullet for large projects. I used a cut-off of 50 since both projects with > 50 samples failed and projects with 45 samples were created without issues. I just mentioned that we don't include them because they are too large and hard to work with.
> Mention that no merged objects are provided for larger projects

- docs/CHANGELOG.md
Towards #268 
This PR adds a changelog entry for merged objects. Do we want more or less detail here?
Note also that this file doesn't have the cell type annotation changelog date in it yet, since we haven't yet dated it, so we'll need to keep tabs on that. It also didn't have the anndata one either (i guess we never merged `main` back into `dev`), so I manually added it.
> Merged object changelog

- docs/CHANGELOG.md
In preparation for the release of merged objects today, this adds the date as the header for the changelog regarding merged objects. Once this is merged into `development` then #285 will be ready to go in and we can do a release.
> Add today's date to changelog for merged objects

- docs/sce_file_contents.md
Following the updates in https://github.com/AlexsLemonade/scpca-nf/pull/742, this documents the addition of `metadata(sce)$demux_methods` in filtered and processed objects.
> Add note about demux_methods

- docs/_static/style.css
Closes #170
This issue updates code link colors as suggested by @dvenprasad: 
>  The link color should be blue (#003595). 
Once approved to go into `development`, we can cherry-pick into the release PRs, so it can go out as part of the `AnnData` release.
> Update code link colors

- components/dictionary.txt
- docs/faq.md
Closes #297 
This PR adds a FAQ for why some samples are unavailable to download as AnnData objects. I used the same overall structure that we use to explain why some merged objects aren't available. I was struggling with the explanation of why we don't include AnnData for multiplexed libraries, so any guidance there would be greatly appreciated!
> FAQ for why AnnData isn't available

- components/dictionary.txt
- docs/CHANGELOG.md
This doesn't affect downloads except for the citation information in the README. It seemed useful to include in the CHANGELOG anyway.
> Add preprint info to CHANGELOG

- docs/CHANGELOG.md
We anticipate that the H5 changes will go live on Friday/ over the weekend. This adds the date for Friday to the changelog entry.
> Add date for H5 change

- docs/faq.md
Closes #305 
We have a few scenarios where no annotations are included in the object and no report is produced. This explains why they might be missing to users.
> Add FAQ for why a library may not include cell type annotations

- docs/faq.md
Since we are removing any libraries that have < 2 cells, the second bullet point in this FAQ no longer applies. Even if there's between 2-30 cells, the report and annotations will be present for SingleR and then CellAssign will say "Not run". We indicate this in the SCE contents section so I don't think we need those specifics here. 
I updated this to just mention when cell type annotations aren't present at all which would be cell lines.
> Update FAQ for samples with missing cell type reports

- docs/CHANGELOG.md
- docs/download_files.md
Closes #315 
This PR adds a changelog for the upcoming release of metadata only downloads (expected on Thursday). Here I'm only adding the information about the project metadata downloads as we are planning to release portal wide metadata next sprint and still have some items to discuss. Because of this I also commented out the line that describes portal wide metadata. Are we okay with this? I'll file an issue to un comment out that line and then probably another changelog and release for when that metadata is available. 
I plan to release these docs on Thursday and will check with @davidsmejia before release. If we need to adjust the date for any reason we can always do that prior to release.
> Add changelog for metadata only downloads

- docs/CHANGELOG.md
Just mirroring the changes made in #322 and also fixing the link in the new changelog additions from #320.
> Fix broken links in changelog in development

- docs/getting_started.md
- docs/merged_objects.md
- docs/sce_file_contents.md
Closes #337 
Related to changes described in https://github.com/AlexsLemonade/scpca-nf/issues/773 and made in https://github.com/AlexsLemonade/scpca-nf/pull/774. 
Here I'm accounting for the new changes to contents in the individual and merged AnnData objects. Both objects have the following changes: 
- `X_PCA` and `X_UMAP` have been renamed to `X_pca` and `X_umap`
- `highly_variable` is now a column in the `.var` slot indicating if a gene is part of the HVG list 
Just the individual objects will have: 
- A new `.uns["pca"]` object that contains information about parameters and variance for PCA. I didn't describe every element of this, because I think if someone is using it they know what they're doing. Let me know if the explanation that I included is okay or if I should add more detail. …
> Updates to AnnData contents based on new scanpy compatibility

- docs/faq.md
- docs/processing_information.md
Dear ScPCA team,
As discussed in #347, I updated alevin-fry references in the doc. Moreover, I noticed the doc says "we used `salmon alevin` and `alevin-fry`". I guess what we wanted to say was the `salmon` mapper, instead of `salmon alevin`, which is for quantification instead of mapping. 
Hope what I changed make sense. Thank you very much!
Best,
Dongze
> update alevin-fry and salmon references

- docs/CHANGELOG.md
- docs/faq.md
I am adding an FAQ that explains the Copy Download Link button on the Portal. Per the issue, I am also adding a short CHANGELOG entry.
Closes #345 - I am choosing to go directly to `main` here, given the small scope, and we'll follow up with a merge `main` -> `development`.
If this release required a CHANGELOG entry, it should be today's date.
> Add `Copy Download Link` FAQ

- components/dictionary.txt
- docs/CHANGELOG.md
- docs/download_files.md
Closes #354 
Closes #355 
Here, I'm removing `sample_cell_count_estimate` from the table describing metadata in non-multiplexed samples and adding a sentence describing the new `demux_sample_cell_estimate` in the multiplexed section.
> Update cell count-related fields description

- docs/CHANGELOG.md
- docs/download_files.md
Addresses #367 
My plan – as described in https://github.com/AlexsLemonade/scpca-docs/issues/367#issuecomment-2478895224 – is to merge `development` -> `main` after this and cut a new release. I don't believe a CHANGELOG entry is required, as this is correcting documentation about the current downloadable files.
> Replace `demux_sample_cell_estimate` with `demux_cell_count_estimate`

- docs/CHANGELOG.md
- docs/download_files.md
Syncing changes in #370 to main. This will be followed by a release.
Closes #367
~~If this release required a CHANGELOG entry, it should be today's date.~~
> Syncing #370 to `main`

- docs/CHANGELOG.md
- docs/download_files.md
Stacked on #373 
Here, I'm updating the three instances where we discuss bulk files in the downloadable files section. I tried to be consistent with how we discuss accession identifiers in filenames in that section.
I am also updating the 2024.08.13 CHANGELOG entry, as this change went into effect on 2024-07-31 per https://github.com/AlexsLemonade/scpca-docs/issues/368#issuecomment-2479528007.
> Update downloadable files section and 2024.08.13 CHANGELOG entry to reflect bulk filenames

- docs/download_files.md
Closes #377 
Just updating the link to the correct location on the 10x site describing the [`spatial`](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/spatial) output. I checked the other 10x links we have and everything else is fine.
> Update spatial link 

- docs/CHANGELOG.md
Closes #403 
⚠️ Stacked on #405 
Here I'm adding a changelog entry for the addition of the consensus cell types and mentioning the change in the merged matrix format. I mostly included links for where they can learn more about the consensus labels, but let me know if I should include more detail here. 
Note that we will need to add the date once we actually are ready to release these changes, which will be done as part of completing #404.
> Add changelog entry for consensus cell types

- docs/download_files.md
Closes #391 
Here I am starting the changes to the `Downloadable files` page to reflect the new [IA](https://data-lab-knowledge.slab.com/posts/sc-pca-docs-ia-changes-for-cart-0y0xuuc0). Since this is the first PR where I'm starting to change things around, I also included some general reorganization of headers to reflect the IA and added in TODOs for sections that will need to be filled out. 
I mostly kept the intro the same, but added in some sentences mentioning there are three ways to download things - picking a single project, making a custom dataset, and downloading one of the portal-wide options. Here I linked to each of the three sections that will talk about these downloads in more detail. 
I filled in the project download section, which will include the screenshots for …
> Add project downloads section

- components/dictionary.txt
- docs/download_files.md
- docs/download_options.md
- docs/index.md
Closes #386 
Closes #387 
This PR initiates the `download_options.md` file with a brief introductory section, and I went ahead and wrote both the data format and modality sections. I decided to do these both at once since I felt they were highly related and it might be helpful to review these together for full context. They are fairly short either way so this shouldn't be a major lift! Let me know if there are more details that you think would be worth including here. For example, I thought at one point maybe we could say something in Data Formats about how bulk is TSV, but that also felt a bit out of scope and like a finer detail to leave out of this document so I nixed it while writing. 
As part of this, no existing FAQ or download files sections (unless we really want to link the full …
> Add data format and modalities sections

- docs/download_options.md
Closes #388
**(Edit) Stacked on #413**
This PR adds a section for merged objects. I first state that merged objects are available when all samples are downloaded, link out to the merged docs, and remind everyone that we don't integrate. Then, I describe how this works for "My Dataset". Finally, I note that the full portal download, when merged, is not _all merged_ but still merged per-project.
Something I think might be missing is an explicit statement about "Download Now," but I felt that that comes across when describing what happens when you download all samples for a project well enough. Please let me know if you disagree and something more explicit would be helpful!
> Add "merge options" section

- docs/download_files.md
- docs/download_options.md
Closes #410 
Closes #396 
Closes #392 
Closes #393 
Closes #394 
This PR fills out the majority of the portal-wide download section. I was going to start with just the intro and then the first section, but it really made more sense to flush it out and get things in the place that I think makes the most sense. The only thing I didn't yet fill out is the spatial section, since that involves more changes throughout the document. 
In working on this, I decided to first have some sentences explaining what the portal wide downloads are and then I stubbed in images for the directory structure when downloading the SCE and AnnData formats. I don't think there's any more text to talk about those, so we just need to add in the images.
I then have a section talking about downloading as merged objects …
> Fill out portal-wide section 

- docs/download_options.md
Closes #389 
This PR adds a section stating that multiplexed samples can be optionally excluded from project downloads. I linked a couple other spots in documentation with some more caveats related to multiplexed data downloads/files as well. It's pretty short but I think this pretty much covers it? Please let me know what other details you think I might be missing here!
> Add section on multiplexed options

- docs/download_options.md
- docs/faq.md
Closes #398 
This PR adds an FAQ explaining that only one data format is available at a time. I also link this FAQ in the data format section of `download_options`. The issue here also suggested stating that you can empty or download your cart if you want to make a new one, but I didn't include that specific detail since it seemed to me to be well-captured by the concept "you need to do two carts to get both formats." Let me know if you disagree and we should indeed be more explicit!
Edit: As noted in the issue since this wasn't slated for this sprint, we can wait to review until next sprint if you prefer!
> Add FAQ: one format at a time

- docs/faq.md
- docs/getting_started.md
Closes #399 
This PR adds an FAQ that you can't get a merged object for a subset of samples. I link to the getting started docs that explain how to subset a merged object as our recommendation instead. Let me know if you think there are any other details or relative links to include.
I also caught a couple things to fix in `getting_started.md` while I was here!
> Add section that you can't merge sample subsets

- docs/download_files.md
- docs/download_options.md
⚠️ Stacked on #414 
Closes #395 
Closes #397 
Here I'm making some minor changes to make sure we account for spatial options throughout the download files section. These were pretty minimal since we already had a detailed spatial section outlining what's included with a spatial library. I mostly added in sentences that linked to that section when necessary and then added one more image for the spatial Portal-wide download structure. 
Once this goes in then I believe that should be everything for text changes to the Download files section and all that will be left to do is update all the images and fix any TODOs.
> Update remaining sections of download files

- docs/faq.md
Closes #400
*formerly **Stacked on #420**
This PR adds an FAQ section about when project options change when appending more samples. I based it off of this section of our Slab notes which describes rules: https://data-lab-knowledge.slab.com/posts/list-of-cart-related-doc-changes-j1e56gnm#hleq5-appending-to-my-dataset-and-how-we-decide-to-apply-project-options
I'm going to request reviews from both @allyhawkins  and @dvenprasad for this one, since I really want to make sure my language is precise!
> FAQ: project options changed after appending

- docs/CHANGELOG.md
- docs/download_files.md
- docs/faq.md
Closes #401
Stacked on #421
This PR adds a section on regenerating datasets to explain that only one version is available at a time as well as information about how to learn more about what version has been downloaded. Again, I'm going to request 2x review here to be sure on phrasing and scope!
While I was here, I also realized a couple other things to fix:
- The columns with workflow information had not been documented as metadata columns, so I went ahead and did that
- The associated text at the top of the CHANGELOG file did not indicate that this info is available in the spatial metadata file, but I confirmed that it is, so I went ahead and updated that text too
> FAQ for regenerating datasets

- .github/workflows/spell-check.yml
In this PR I'm adding `the-manuscript` to the branches where the spell check action should be run. I'm pretty sure this will work to send this PR directly to `the-manuscript` branch (as in I don't think it needs to be committed to in `main`), but in case I'm wrong we'll find out soon enough as PRs come in :) 
I put it in quotes too, since don't know about that dash.
> Turn on spell check
