- docs/download_files.md
Related to #6 
Added illustrations to the section.
> Added download illustrations

- docs/processing_information.md
- docs/sce_file_contents.md
Closes #50
Here I am adding a few minor comments to note that we are rounding expression counts to integer values. I didn't go into detail about why the results might not be integers to start with, because I thought that was probably getting a bit too detailed and might confuse more than enlighten. So just a few little additions.
> Add notes on rounding

- components/dictionary.txt
- docs/getting_started.md
- docs/index.md
- docs/sce_file_contents.md
Closes #52. 
Here I'm adding the section on how to get started using an Scpca dataset. I've included sections on importing the RDS files into R, quality control, normalization, downstream analysis, and then working with Seurat. 
In the first section I included a short introduction on the two RDS files that are present for each sample and linked out to other sections in the docs when necessary. We do have a FAQ that explains reading into R, but I remembered we talked about repeating some of that information and it seemed like a necessary first step. 
For the quality control section, I included information about using `miQC` and how we have presence of the `miQC_pass` column in the objects. I have some explanation on what `miQC` is along with links to the vignette and documentation. I also …
> Create a getting started with scpca data section 

- docs/_templates/layout.html
#60  Added the provided script to `_templates/layout.html`
> #60 - add hotjar script

- components/dictionary.txt
- docs/processing_information.md
I was looking at what I had written for the genetic demux and noticed that the references were incomplete and somewhat inconsistent. this PR cleans them up, and fixes a couple other little things I noticed in the same document.
> Update references for genetic demux

- docs/processing_information.md
Merge this when the spatial transcriptomics data is available.
> Remove Data will be available line

- docs/processing_information.md
Multiplexed data is currently being processed to be made available on production, this is the update to the docs that reflects that change.
* removes "Data Available Soon" message
> Multiplexed Data Available

- docs/conf.py
- docs/download_files.md
- docs/faq.md
- docs/processing_information.md
- docs/sce_file_contents.md
This PR fixes some miscellaneous typos and such, _including one 404'd link_!, in the docs. These are just what I noticed when reviewing docs in prep for presenting the ScPCA poster.
> Misc doc fixes

- docs/sce_file_contents.md
Companion PR to https://github.com/AlexsLemonade/scpca-nf/pull/492 - updates docs to match.
> Update cluster column name

- .readthedocs.yaml
Same as #177, just syncing this with `documentation-improvements`
> Syncing build changes into documentation-improvements protected branch

- .github/workflows/spell-check.yml
We have a bunch of PRs incoming that could probably use spell checking at the time of pull request, so I'm adding `documentation-improvements` to the list of branches that trigger the spell check GHA. This probably only needs to go in in this branch?
> Add documentation-improvements branch to spell check

- docs/CHANGELOG.md
Closes #189 
Here, I created a new entry in the Changelog that includes everything relevant to AnnData additions. I added a placeholder for the heading that will need to be replaced with the date of release when the time comes. 
- Are there any items that you think are not relevant to be in the Changelog entry? 
- Are there any items that should be there that are missing? (I didn't include mention of the clustering assignments, but I could)
> Add new section for AnnData in Changelog

- docs/index.md
Replacing the outdated ScPCA tagline with the new one!
This PR addresses #212.
> Updating docs with new ScPCA tagline

- docs/download_files.md
I changed `_qc_report.html -> _qc.html`.
FYI no parallel change needed in `scpca-nf` - https://github.com/AlexsLemonade/scpca-nf/blob/f08ce452f95f88e169217c114aef1c1321a3688c/modules/qc-report.nf#L17
> Change one more name

- docs/faq.md
Here I'm adding a FAQ to explain why some libraries were previously there but might be missing. I tried to focus on the quality control and mentioned that we do not do any screening. 
I'm also filing this to `main` based on our discussion in Slack. We don't need to release this immediately, but it will now be included in the next release. If we prefer to add it to `development` and then to the AnnData release branch, I can move it there. 
Closes #143 
If this release required a CHANGELOG entry, it should be today's date.
> Add FAQ for libraries that get removed

- docs/faq.md
- docs/getting_started.md
Closes #220 
This PR adds an FAQ section about why choose a merged object. Let me know where I can expand or rephrase here! 
Also, any suggestions for the section header text itself? I have `When should I download a merged object?`, but could incorporate the word "choose" too.
> FAQ docs: why choose a merged object?

- docs/getting_started.md
- docs/merged_objects.md
- docs/sce_file_contents.md
Closes  #265 
Does what it says and updates strings from `id` -> `ID`.
> Change id -> ID

- docs/processing_information.md
Closes #270 
I've added a quick caveat sentence to the docs here.
I'll cherry-pick this into the cell type release once it goes into `development`.
> No tumor in reference data

- docs/faq.md
Closes #274 
This PR updates the FAQ section about projects without merged objects, following changes in `scpca-nf` in https://github.com/AlexsLemonade/scpca-nf/pull/719.
> Update merged FAQ 

- docs/CHANGELOG.md
- docs/faq.md
This is just to sync up `main` and `development` as there were a few changes there that were potentially going to end up as conflicts...
> Merge 2024.04.11 changes into development branch

- docs/faq.md
Here I'm changing the max number of samples to create a merged object from 50 to 100.
> Change threshold for merged objects from 50 to 100

- docs/CHANGELOG.md
I realized that while the bullet point text required for #294 was present, the placeholder header was not updated properly, so here I am doing that.
> Update CHANGELOG.md placehodler header

- components/dictionary.txt
- docs/citation.md
Closes #296. I removed the APA and MLA citations for the Portal itself.
> Add citation for bioRxiv preprint

- docs/CHANGELOG.md
This is the one thing I caught that needed fixing in #301
> Add backticks

- docs/CHANGELOG.md
Fixing a broken link (formatting) in the changelog.
> Fix Changelog link

- docs/CHANGELOG.md
- docs/download_files.md
https://github.com/AlexsLemonade/scpca-docs/pull/341/files#r1715633639
https://github.com/AlexsLemonade/scpca-docs/pull/341/files#r1715630194
> Add back portal-wide metadata changes to `development`

- docs/CHANGELOG.md
⚠️ Stacked on #359 
Closes #356 
This pull request adds a CHANGELOG entry for the cell count-related fields described in #359 and a bullet about the fusion nomenclature standardization.
> Add CHANGELOG entry for cell count-related changes and fusion update

- docs/CHANGELOG.md
Closes #362 
Here I added two bullet points to the changelog to cover the change to the count matrix and the column name changes that were made. I don't know if I love my wording for any of these, so feel free to tell me it is bad.
> Update changelog with counts and capitals

- docs/CHANGELOG.md
Adding the date as part of https://github.com/AlexsLemonade/scpca-docs/issues/364
> Add date for latest CHANGELOG entry

- docs/CHANGELOG.md
Merging `development` into `main` for https://github.com/AlexsLemonade/scpca-docs/issues/364
> Merge in development for Nov 14 release

- docs/download_files.md
> Spatial link change in `main`
